### ISSUE TITLE
Please add a README in English

### ISSUE THREAD

**Issue by pcav** [Kanahiro/qgis-nowcast-tool-plugin#1]
So more people will be able to understand your plugin.
Arigatou!

**Comment by Kanahiro** [comment]
Thank you for your interest.

This plugin is utility for Nowcast raster-tiles opened by Japan Meteorological Agency - https://www.jma.go.jp/jma/index.html .
Nowcast tile covers Japan-area so that it is useful for Japanese. Therefore, translation for other languages is not important for me, sorry.

If many people want to do so, I will re-think to do.

**Comment by pcav** [comment]
Please add this note to the About, otherwise an user will not know that it is Jana only.
Thanks.
